name: Docker Build and Push

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        docker build -f .devcontainer/Dockerfile -t cristiantr/dev_container_image:${{ env.TAG }} .
        docker push cristiantr/dev_container_image:${{ env.TAG }}


    - name: Update latest tag
      run: |
        docker tag cristiantr/dev_container_image:${{ env.TAG }} cristiantr/dev_container_image:latest
        docker push cristiantr/dev_container_image:latest